### ISSUE TITLE
Where can I find the reference for the function scan_params?

### ISSUE THREAD

**Issue by Hanros94** [HaeffnerLab/artiq-work-lattice#1]
Hi 

I would like to first of all thank you for uploading this code. Could you please tell me where I can find the files explaining accessed_params and scan_params?
Where can I find references to artiq.pulse_sequence?

**Comment by rmshaffer** [comment]
The `pulse_sequence` class (which uses `accessed_params` and `scan_params`) is defined in:
https://github.com/HaeffnerLab/artiq/blob/master/artiq/.pulse_sequence/pulse_sequence.py.
